version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"